// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkApi.Models;

#nullable disable

namespace ParkApi.Migrations
{
    [DbContext(typeof(ParkApiContext))]
    [Migration("20230420172916_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParkApi.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<bool>("National")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.HasKey("ParkId");

                    b.ToTable("Park");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Name = "Crater Lake",
                            National = true,
                            State = "Oregon"
                        },
                        new
                        {
                            ParkId = 2,
                            Name = "Ainsworth",
                            National = false,
                            State = "Oregon"
                        },
                        new
                        {
                            ParkId = 3,
                            Name = "Bates",
                            National = false,
                            State = "Oregon"
                        },
                        new
                        {
                            ParkId = 4,
                            Name = "Angel Island",
                            National = false,
                            State = "California"
                        },
                        new
                        {
                            ParkId = 5,
                            Name = "Van Damme",
                            National = false,
                            State = "California"
                        },
                        new
                        {
                            ParkId = 6,
                            Name = "Yosemite",
                            National = true,
                            State = "California"
                        },
                        new
                        {
                            ParkId = 7,
                            Name = "Joshua Tree",
                            National = true,
                            State = "California"
                        },
                        new
                        {
                            ParkId = 8,
                            Name = "Big Bend",
                            National = true,
                            State = "Texas"
                        },
                        new
                        {
                            ParkId = 9,
                            Name = "Big Spring",
                            National = false,
                            State = "Texas"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
